nelmio_cors:
    defaults:
        allow_credentials: true
        origin_regex: true
        allow_origin: []
        allow_methods: []
        allow_headers: ['*']
        expose_headers: []
        max_age: 0
    paths:
        '^/api':
            origin_regex: true
            allow_origin: ['*']
            allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE']
            allow_headers: ['*']
            expose_headers: []
            max_age: 3600